print("Hello\nWorld")
name = input("Enter your name : ")
age = input("Enter your age : ")
print("Hello " + name + "! You are " + age)
print(name.upper() + " IS COOL")
print(name.lower().islower())
print(name.upper().islower())
print(len(name))
print(name[0])